conky.config = {
--==============================================================================

--  This theme is for conky version 1.10.8 or newer
--  author  : NoSweatSuperDry
--  license : Distributed under the terms of GPLv3
--  notes   : Created on 2560x1440 Monitor

--==============================================================================

-- Size and Position settings --
  alignment = 'top_left',
  gap_x = -1860,
  gap_y = 50,
  maximum_width = 600,
  minimum_height = 520,
  minimum_width = 600,
  
-- Text settings --
  use_xft = true,
  override_utf8_locale = true,
  font = 'Dosis:size=1',
  
-- Color Settings --
  default_color = '#f9f9f9',
  default_outline_color = 'white',
  default_shade_color = 'white',
  color1 = '#212021',
  
-- Window Settings --
  background = false,
  border_width = 1,
  draw_borders = false,
  draw_graph_borders = false,
  draw_outline = false,
  draw_shades = false,
  own_window = true,
  own_window_colour = '#FFFFFF',
  own_window_class = 'Conky',
  own_window_argb_visual = true,
  own_window_argb_value = 0,
  own_window_type = 'desktop',
  own_window_transparent = true,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  stippled_borders = 0,
  
-- Others --
  cpu_avg_samples = 2,
  net_avg_samples = 2,
  double_buffer = true,
  out_to_console = false,
  out_to_stderr = false,
  extra_newline = false,
  update_interval = 1,
  uppercase = false,
  use_spacer = 'none',
  show_graph_scale = false,
  show_graph_range = false
}

conky.text = [[
${execi 200 ~/.config/conky/Altair/scripts/weather.sh}\
${font Dosis:bold:size=70}${time %I:%M}${font}${font Dosis:size=25} ${time %p}${font}
${voffset 2}${font Dosis:size=20}${time %A, %d %B}${font}

${voffset 10}${font Dosis:bold:size=12}SYSTEM${font}
${font Dosis:size=10}-----------------------${font}

${font Feather:size=10}${font Dosis:size=11} Uptime
${goto 160}${font Dosis:size=11}${uptime}${font}

${voffset 2}${font Feather:size=10}${font Dosis:size=11} CPU
${goto 160}${font Dosis:size=11}${cpu cpu0}%${font}
${voffset 2}${cpubar 8,260 cpu0}
${voffset 2}${cpugraph 18,260}

${voffset 2}${font Feather:size=10}${font Dosis:size=11} RAM
${goto 160}${font Dosis:size=11}${memperc}% (${mem} / ${memmax})${font}
${voffset 2}${membar 8,260}

${voffset 2}${font Feather:size=10}${font Dosis:size=11} Disk /
${goto 160}${font Dosis:size=11}${fs_used_perc /}% (${fs_used /} / ${fs_size /})${font}
${voffset 2}${fs_bar 8,260 /}

${voffset 2}${font Feather:size=10}${font Dosis:size=11} GPU
${goto 160}${font Dosis:size=11}${execi 2 nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits}%${font}
${voffset 2}${execbar 8,260 nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits}

${voffset 2}${font Feather:size=10}${font Dosis:size=11} GPU Temp
${goto 160}${font Dosis:size=11}${execi 5 nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader}°C${font}

${voffset 10}${font Dosis:bold:size=12}ETHERNET${font}
${font Dosis:size=10}-----------------------${font}

${font Feather:size=10}${font Dosis:size=11} Up
${goto 160}${font Dosis:size=11}${upspeed enp3s0}${font}
${voffset 2}${upspeedgraph enp3s0 18,260}

${voffset 2}${font Feather:size=10}${font Dosis:size=11} Down
${goto 160}${font Dosis:size=11}${downspeed enp3s0}${font}
${voffset 2}${downspeedgraph enp3s0 18,260}

${voffset 20}${offset 0}${font feather::size=55}${execi 15 ~/.config/conky/Altair/scripts/weather-text-icon}\
${goto 100}${voffset -10}${font Dosis:bold:size=45}${execi 100 cat ~/.cache/weather.json | jq '.main.temp' | awk '{print int($1+0.5)}'}°${font}

${offset 190}${voffset -51}${font Dosis:bold:size=20}${execi 100 cat ~/.cache/weather.json | jq -r '.weather[0].description' | sed "s|\<.|\U&|g"}${font}
${offset 190}${voffset 2}${font Dosis:Italic:size=10}Wind ${execi 100 cat ~/.cache/weather.json | jq '.wind.speed'}  Hum ${execi 100 cat ~/.cache/weather.json | jq '.main.humidity'}%${font}
]]
